Added login-  components, service and model
livstella/mefit pull request #1
Opened 2022-03-08 12:16 UTC by MichelSaremi

2022-03-08 12:30 UTC, livstella requested changes
Som udgangspunkt ser det jo fint ud for mig:-) 
Dog tænker jeg ikke umiddelbart at vi har en api key som du bruger i login.service.ts. Eller har jeg overset det? 
Og skal vi gemme "current user" i local storage? Ellers tænker jeg det godt kan sættes op som en POST request selvom vores endpoint er tomt:-) 

I må sige til hvis jeg misforstår.

2022-03-08 13:11 UTC, Epiko1994 commented
Jeg er enig i det Liv nævner.
Regner ikke med at vi kommer til at have noget password på vores API, så api key bliver nok ikke nødvendigt.
Derudover skal current user vel gemmes i Session ikke local storage?

2022-03-09 07:57 UTC, Epiko1994 approved these changes

2022-03-09 10:11 UTC, livstella approved these changes

2022-03-09 10:11 UTC, merged