Time date
livstella/mefit pull request #36
Opened 2022-03-23 16:16 UTC by MichelSaremi

2022-03-24 11:11 UTC, livstella commented on src/app/components/goal-dashboard/goal-dashboard.component.html
> +                <button id="day-buttons" class="day-buttons" (click)="increment_day1_10(item.key)">+10</button>
Id bør ikke være det samme

2022-03-24 11:11 UTC, livstella commented on src/app/components/goal-dashboard/goal-dashboard.component.html
> +                <button id="day-buttons" class="day-buttons" (click)="remove_day2(item.key)">Remove</button>
Hele vejen her til

2022-03-24 11:12 UTC, livstella commented on src/app/components/goal-dashboard/goal-dashboard.component.html
> +                <button id="day-buttons" class="day-buttons" (click)="remove_day7(item.key)">Remove</button>
Jeg tog fejl, helt hertil. Det er ikke et id

2022-03-24 11:16 UTC, livstella commented on src/app/components/goal-dashboard/goal-dashboard.component.ts
> +    this.disable();
Skal alt disables?

2022-03-24 11:18 UTC, livstella commented on src/app/components/goal-dashboard/goal-dashboard.component.ts
>         localStorage.removeItem("daily_finish")
Og det er derfor jeg ikke er fan af hardcodet løsning og gentagen kode. Der er stor fare for at vi overser noget her.

2022-03-24 11:19 UTC, livstella commented on src/app/components/goal-dashboard/goal-dashboard.component.ts
> +     this.daySeven = this.oneDate.getFullYear()+"-"+(this.oneDate.getMonth()+1)+"-"+this.oneDate.getDate()
https://github.com/livstella/mefit/pull/36/files#r834195833 

Ovenstående kommentar gælder selvfølgelig hel herned til. 200 linjer hvor vi skal sikre vi ikke har misset en +1. Jeg er lidt bekymret for at bruge denne løsninng

2022-03-24 11:21 UTC, livstella requested changes
See single comments for changes. At least id needs to be changed. We cannot have the same ID this many times

2022-03-24 11:25 UTC, MichelSaremi commented on src/app/components/goal-dashboard/goal-dashboard.component.ts
> +    this.disable();
ja alt hvad der kan ændre goal after commit disables

2022-03-24 11:31 UTC, Epiko1994 reviewed
Jeg ved godt det er lidt sent at sige nu, hvor dashboard er merged, men jeg fandt lige ud af at der bliver smidt tekst på siden fra javascripten. Det er noget bæ at arbejde med. xD

2022-03-27 14:57 UTC, MichelSaremi commented on src/app/components/goal-dashboard/goal-dashboard.component.html
> +                <button id="day-buttons" class="day-buttons" (click)="increment_day1_10(item.key)">+10</button>
Alle id er fjernet i nyt pull request

2022-03-28 12:40 UTC, closed without merging